### ISSUE TITLE
Naruto psx

### ISSUE THREAD

**Issue by Henrixmoli** [juanoliveira82/naruto-ps1_translation-english#1]
Bro sigues en el proyecto para traducir el juego?

**Comment by Henrixmoli** [comment]
Bro I would like to help you in this project, so that at least the game is understood and is more playable

**Comment by mvreisg** [comment]
May you allow Pull Requests?

**Comment by mvreisg** [comment]
I can't commit my changes. Would you like to allow?

**Comment by juanoliveira82** [comment]
You have to fork the repo, make your changes and then you create a pull request to my repo.

Right now there is not a pull request that I can review.

**Comment by mvreisg** [comment]
Oh okay, thanks! :)
